# Generated by Django 4.1.5 on 2023-03-13 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.CharField(default=None, max_length=2056)),
                ('visible', models.BooleanField(default=True)),
                ('added_by', models.IntegerField()),
                ('add_date', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 11, 42, 26, 803411, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.CharField(default=None, max_length=2056)),
                ('visible', models.BooleanField(default=True)),
                ('added_by', models.IntegerField()),
                ('add_date', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 11, 42, 26, 803876, tzinfo=datetime.timezone.utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('img', models.CharField(default=None, max_length=2056)),
                ('added_by', models.IntegerField()),
                ('add_date', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 11, 42, 26, 804304, tzinfo=datetime.timezone.utc))),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('add_date', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 11, 42, 26, 804654, tzinfo=datetime.timezone.utc))),
                ('accepted', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
