# Generated by Django 4.1.5 on 2023-03-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_maincategory_add_date_alter_opinions_add_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.maincategory'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
