# Generated by Django 4.1.5 on 2023-03-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_subcategory_product_maincategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.maincategory'),
        ),
    ]
