# Generated by Django 4.1.5 on 2023-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='img',
            field=models.FileField(upload_to='media/products/categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to='media/prodcuts/products'),
        ),
    ]
