# Generated by Django 4.1.5 on 2023-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_maincategory_img_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to='media/prodcuts/products/'),
        ),
    ]
