# Generated by Django 4.1.5 on 2023-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('verificated', models.BooleanField(default=False)),
                ('texted_back', models.BooleanField(default=False)),
            ],
        ),
    ]
