# Generated by Django 4.1.5 on 2023-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_maincategory_alter_maincontactform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='img',
            field=models.CharField(default=None, max_length=2056),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default=None, max_length=2056),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.CharField(default=None, max_length=2056),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
