# Generated by Django 4.1.5 on 2023-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_maincategory_img_maincategory_visible_product_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOpinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('add_date', models.DateTimeField()),
                ('accepted', models.BooleanField()),
                ('visible', models.BooleanField()),
            ],
        ),
    ]
