# Generated by Django 4.1.5 on 2023-02-25 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_companyopinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 47, 31, 637108)),
        ),
        migrations.AlterField(
            model_name='companyopinions',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyopinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 47, 31, 638736)),
        ),
        migrations.AlterField(
            model_name='companyopinions',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 47, 31, 637409)),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 47, 31, 638437)),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 47, 31, 638114)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 47, 31, 637668)),
        ),
    ]
