# Generated by Django 4.1.5 on 2023-02-25 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_companyopinions_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyopinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 50, 25, 179615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 50, 25, 177885, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='maincontactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 50, 25, 177480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 50, 25, 179287, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 50, 25, 178933, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 50, 25, 178316, tzinfo=datetime.timezone.utc)),
        ),
    ]
