# Generated by Django 4.1.5 on 2023-02-25 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_companyopinions_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyopinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 51, 23, 219121, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 51, 23, 217537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='maincontactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 51, 23, 217133, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 51, 23, 218786, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 51, 23, 218380, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 18, 51, 23, 217828, tzinfo=datetime.timezone.utc)),
        ),
    ]
