# Generated by Django 4.1.5 on 2023-03-05 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_companyopinions_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyopinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 21, 7, 27, 431975, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 21, 7, 27, 430602, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='maincontactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 21, 7, 27, 430249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 21, 7, 27, 431657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 21, 7, 27, 431296, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 21, 7, 27, 430972, tzinfo=datetime.timezone.utc)),
        ),
    ]
