# Generated by Django 4.1.5 on 2023-03-13 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_opinions_product_remove_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyopinions',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 11, 43, 21, 597630, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='maincontactform',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 11, 43, 21, 597251, tzinfo=datetime.timezone.utc)),
        ),
    ]
